import type { Metadata } from "next"
import "./globals.css"
import Footer from "./_components/footer"
import AuthProvider from "./providers/auth"

// const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "MarcaFlex",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <AuthProvider>
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}
