import type { Metadata } from "next"
import "./globals.css"
import Footer from "./_components/footer"
import AuthProvider from "./providers/auth"

import { Toaster } from "./_components/ui/sonner"

export const metadata: Metadata = {
  title: "MarcaFlex",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <AuthProvider>
          <div className="flex h-full flex-col">
            <div className="flex-1">{children}</div>
            <Toaster />
            <Footer />
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
